#!/usr/bin/env bash
set -euo pipefail

to_pascal_case() {
  echo "$1" | sed -r 's/(^|-)([a-z])/\U\2/g'
}

to_camel_case() {
  local pascal
  pascal=$(to_pascal_case "$1")
  echo "$(tr '[:upper:]' '[:lower:]' <<< "${pascal:0:1}")${pascal:1}"
}

SRC_DIR="src"
SUBDIRS=("entities" "repositories" "schemas" "services")

DOMAIN_NAME_KEBAB="$1"
DOMAIN_DIR="$SRC_DIR/$DOMAIN_NAME_KEBAB"

ENTITY_CLASS=$(to_pascal_case "$DOMAIN_NAME_KEBAB")
ENTITY_PREFIX=$(to_camel_case "$DOMAIN_NAME_KEBAB")

mkdir -p "$DOMAIN_DIR"
for dir in "${SUBDIRS[@]}"; do
  mkdir -p "$DOMAIN_DIR/$dir"
done

ENTITY_FILE="$DOMAIN_DIR/entities/${DOMAIN_NAME_KEBAB}.entity.ts"
TEMPLATE_CONTENT=$(<"./scripts/templates/entity-template.txt")

REPLACED_CONTENT="${TEMPLATE_CONTENT//<ENTITY_CLASS>/${ENTITY_CLASS}}"
REPLACED_CONTENT="${REPLACED_CONTENT//<DOMAIN_NAME>/${DOMAIN_NAME_KEBAB}}"
REPLACED_CONTENT="${REPLACED_CONTENT//<ENTITY_PREFIX>/${ENTITY_PREFIX}}"
echo "$REPLACED_CONTENT" > "$ENTITY_FILE"

REPO_FILE="$DOMAIN_DIR/repositories/${DOMAIN_NAME_KEBAB}-repository.ts"
REPO_TEMPLATE_CONTENT=$(<"./scripts/templates/repository-template.txt")

REPLACED_REPO_CONTENT="${REPO_TEMPLATE_CONTENT//<ENTITY_CLASS>/${ENTITY_CLASS}}"
REPLACED_REPO_CONTENT="${REPLACED_REPO_CONTENT//<DOMAIN_NAME>/${DOMAIN_NAME_KEBAB}}"
REPLACED_REPO_CONTENT="${REPLACED_REPO_CONTENT//<ENTITY_PREFIX>/${ENTITY_PREFIX}}"
REPLACED_REPO_CONTENT="${REPLACED_REPO_CONTENT//<DOMAIN_NAME^>/${ENTITY_CLASS}}"
echo "$REPLACED_REPO_CONTENT" > "$REPO_FILE"

SCHEMA_FILE="$DOMAIN_DIR/schemas/${DOMAIN_NAME_KEBAB}.ts"
SCHEMA_TEMPLATE_CONTENT=$(<"./scripts/templates/schema-template.txt")

REPLACED_SCHEMA_CONTENT="${SCHEMA_TEMPLATE_CONTENT//<ENTITY_CLASS>/${ENTITY_CLASS}}"
REPLACED_SCHEMA_CONTENT="${REPLACED_SCHEMA_CONTENT//<DOMAIN_NAME>/${DOMAIN_NAME_KEBAB}}"
REPLACED_SCHEMA_CONTENT="${REPLACED_SCHEMA_CONTENT//<ENTITY_PREFIX>/${ENTITY_PREFIX}}"
echo "$REPLACED_SCHEMA_CONTENT" > "$SCHEMA_FILE"

SERVICE_FILE="$DOMAIN_DIR/services/manage-${DOMAIN_NAME_KEBAB}.ts"
SERVICE_TEMPLATE_CONTENT=$(<"./scripts/templates/service-template.txt")

REPLACED_SERVICE_CONTENT="${SERVICE_TEMPLATE_CONTENT//<ENTITY_CLASS>/${ENTITY_CLASS}}"
REPLACED_SERVICE_CONTENT="${REPLACED_SERVICE_CONTENT//<DOMAIN_NAME>/${DOMAIN_NAME_KEBAB}}"
REPLACED_SERVICE_CONTENT="${REPLACED_SERVICE_CONTENT//<ENTITY_PREFIX>/${ENTITY_PREFIX}}"
echo "$REPLACED_SERVICE_CONTENT" > "$SERVICE_FILE"

ROUTER_FILE="$DOMAIN_DIR/routers.ts"
ROUTER_TEMPLATE_CONTENT=$(<"./scripts/templates/router-template.txt")

REPLACED_ROUTER_CONTENT="${ROUTER_TEMPLATE_CONTENT//<ENTITY_CLASS>/${ENTITY_CLASS}}"
REPLACED_ROUTER_CONTENT="${REPLACED_ROUTER_CONTENT//<DOMAIN_NAME>/${DOMAIN_NAME_KEBAB}}"
REPLACED_ROUTER_CONTENT="${REPLACED_ROUTER_CONTENT//<ENTITY_PREFIX>/${ENTITY_PREFIX}}"
echo "$REPLACED_ROUTER_CONTENT" > "$ROUTER_FILE"

echo "Domain '$DOMAIN_NAME_KEBAB' created successfully under '$DOMAIN_DIR'"
